# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: document_extractor_management
defmodule E2e.DocumentExtractorManagementTest do
  use ExUnit.Case, async: false

  describe "document_extractors_clear" do
    test "document_extractors_clear" do
      result = Kreuzberg.clear_document_extractors()
    end
  end

  describe "extractors_list" do
    test "extractors_list" do
      result = Kreuzberg.list_document_extractors()
    end
  end
end
