# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Kreuzberg.clear_post_processors()
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Kreuzberg.list_post_processors()
    end
  end
end
