# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Xberg.list_embedding_backends()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Xberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Xberg.list_post_processors()
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Xberg.list_renderers()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Xberg.list_validators()
    end
  end
end
