# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: rerank_async_pending
defmodule E2e.RerankAsyncPendingTest do
  use ExUnit.Case, async: false

  describe "async_rerank" do
    test "async_rerank" do
      assert {:error, _} = Kreuzberg.rerank_async("neural networks", ["Neural networks are a class of machine learning models inspired by biological brains.", "The Eiffel Tower is located in Paris.", "Convolutional neural networks excel at image recognition tasks."], "{\"model\":{\"name\":\"async_rerank\",\"type\":\"plugin\"}}")
    end
  end
end
