// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: embedding_backend_management.</summary>
    public class EmbeddingBackendManagementTests
    {
        private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_EmbeddingBackendsClear()
        {
            // Clear all embedding backends and verify list is empty
            XbergConverter.ClearEmbeddingBackends();
        }

        [Fact]
        public void Test_EmbeddingBackendsList()
        {
            // List all registered embedding backends
            var result = XbergConverter.ListEmbeddingBackends();

        }


    }
}
