// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergConverter;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: pdf.</summary>
    public class PdfTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_RenderPdfPageFirst()
        {
            // render_pdf_page_to_png: first page
            var result = KreuzbergConverter.RenderPdfPageToPng(System.IO.File.ReadAllBytes("pdf/fake_memo.pdf"), 0, null, null);
            Assert.NotNull(result);
            // skipped: assertion type 'min_length' not supported on byte[] result

        }

        [Fact]
        public void Test_RenderPdfPageOutOfRange()
        {
            // render_pdf_page_to_png: page out of range
            Assert.ThrowsAny<KreuzbergException>(() =>
            {
                KreuzbergConverter.RenderPdfPageToPng(System.IO.File.ReadAllBytes("pdf/fake_memo.pdf"), 999, null, null);
            });
        }


    }
}
