// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergLib;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: post_processor_management.</summary>
    public class PostProcessorManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_PostProcessorsClear()
        {
            // Clear all post-processors and verify list is empty
            KreuzbergLib.ClearPostProcessors();
        }

        [Fact]
        public void Test_PostProcessorsList()
        {
            // List all registered post-processors
            var result = KreuzbergLib.ListPostProcessors();

        }


    }
}
