// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Kreuzberg;
using static Kreuzberg.KreuzbergConverter;

namespace Kreuzberg
{
    /// <summary>E2e tests for category: reranker_backend_management.</summary>
    public class RerankerBackendManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_ClearRerankerBackends()
        {
            // Clear all reranker backends and verify list is empty
            KreuzbergConverter.ClearRerankerBackends();
        }

        [Fact]
        public void Test_ListRerankerBackends()
        {
            // List all registered reranker backends
            var result = KreuzbergConverter.ListRerankerBackends();

        }


    }
}
