// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: detection

use kreuzberg::{detect_mime_type_from_bytes, get_extensions_for_mime};

#[test]
fn test_detect_mime_bytes_html() {
    // Detect HTML MIME from bytes
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/html/html.html"
    ))
    .expect("test_documents/html/html.html must exist");
    let _ = detect_mime_type_from_bytes(&content).expect("should succeed");
}

#[test]
fn test_detect_mime_bytes_pdf() {
    // Detect PDF MIME type from bytes
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/pdf/fake_memo.pdf"
    ))
    .expect("test_documents/pdf/fake_memo.pdf must exist");
    let _ = detect_mime_type_from_bytes(&content).expect("should succeed");
}

#[test]
fn test_detect_mime_bytes_png() {
    // Detect PNG MIME type from bytes
    let content = std::fs::read(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test_documents/images/test_hello_world.png"
    ))
    .expect("test_documents/images/test_hello_world.png must exist");
    let _ = detect_mime_type_from_bytes(&content).expect("should succeed");
}

#[test]
fn test_get_extensions_unknown_mime() {
    // get_extensions unknown MIME
    let mime_type = r#"application/x-totally-unknown"#;
    let result = get_extensions_for_mime(mime_type);
    assert!(result.is_err(), "expected call to fail");
}
