// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: embedding_backend_management

use xberg::{clear_embedding_backends, list_embedding_backends};

#[test]
fn test_embedding_backends_clear() {
    // Clear all embedding backends and verify list is empty
    let _ = clear_embedding_backends();
}

#[test]
fn test_embedding_backends_list() {
    // List all registered embedding backends
    let _ = list_embedding_backends();
}
