// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: registry_operations

use kreuzberg::get_extensions_for_mime;

#[test]
fn test_extensions_docx() {
    // Get file extensions for DOCX MIME type
    let mime_type = r#"application/vnd.openxmlformats-officedocument.wordprocessingml.document"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}

#[test]
fn test_extensions_html() {
    // Get file extensions for HTML MIME type
    let mime_type = r#"text/html"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}

#[test]
fn test_extensions_pdf() {
    // Get file extensions for PDF MIME type
    let mime_type = r#"application/pdf"#;
    let _ = get_extensions_for_mime(mime_type).expect("should succeed");
}
