// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: renderer_management

use kreuzberg::{clear_renderers, list_renderers};

#[test]
fn test_renderers_clear() {
    // Clear all renderers and verify list is empty
    let _ = clear_renderers();
}

#[test]
fn test_renderers_list() {
    // List all registered renderers
    let _ = list_renderers();
}
