# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.AuthConfig do
  @moduledoc "Authentication configuration."

  @typedoc "Authentication configuration."
  @type t :: term()

  @typedoc "HTTP Basic authentication."
  @type basic :: %{type: :basic, username: String.t(), password: String.t()}
  @typedoc "Bearer token authentication."
  @type bearer :: %{type: :bearer, token: String.t()}
  @typedoc "Custom authentication header."
  @type header :: %{type: :header, name: String.t(), value: String.t()}

  def basic(username, password), do: {:basic, %{username: username, password: password}}
  def bearer(token), do: {:bearer, %{token: token}}
  def header(name, value), do: {:header, %{name: name, value: value}}
end
