# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CitationMetadata do
  @moduledoc "Citation file metadata (RIS, PubMed, EndNote)."

  @typedoc "Citation file metadata (RIS, PubMed, EndNote)."
  @type t :: %__MODULE__{
          citation_count: non_neg_integer(),
          format: String.t() | nil,
          authors: [String.t()],
          year_range: Xberg.YearRange.t() | nil,
          dois: [String.t()],
          keywords: [String.t()]
        }

  defstruct citation_count: 0,
            format: nil,
            authors: [],
            year_range: nil,
            dois: [],
            keywords: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
