# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Citation do
  @moduledoc """
  A structured citation from a citation block.

  Parsed from entries like:
  `[^srcN]: source, locator, excerpt: "text"`
  """

  @typedoc "A structured citation from a citation block."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          source: String.t() | nil,
          locator: String.t() | nil,
          excerpt: String.t() | nil
        }

  defstruct label: nil,
            source: nil,
            locator: nil,
            excerpt: nil
end
