# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
