# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CustomGlinerSource do
  @moduledoc """
  Caller-supplied override pointing GLiNER at an arbitrary Hugging Face repo
  instead of the pinned `xberg-io/gliner-models` catalog.

  Files downloaded from a custom repo are **not** checksum-verified — the
  catalog's `checksums.sha256` only covers the pinned models xberg publishes.
  Callers choosing a custom repo are trusting that source directly.
  """

  @typedoc "Caller-supplied override pointing GLiNER at an arbitrary Hugging Face repo instead of the pinned `xberg-io/gliner-models` catalog."
  @type t :: %__MODULE__{
          repo: String.t() | nil,
          model_file: String.t() | nil,
          tokenizer_file: String.t() | nil,
          architecture: String.t() | nil
        }

  defstruct repo: nil,
            model_file: nil,
            tokenizer_file: nil,
            architecture: :gliner1
end
