# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
