# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
