# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentRevision do
  @moduledoc """
  A single tracked change embedded in a document.

  Populated by per-format extractors that understand change-tracking metadata
  (DOCX `w:ins`/`w:del`/`w:rPrChange`, ODT `text:change-*`, …). Every
  extractor defaults to `ExtractedDocument.revisions = None` until a
  format-specific implementation is added.
  """

  @typedoc "A single tracked change embedded in a document."
  @type t :: %__MODULE__{
          revision_id: String.t() | nil,
          author: String.t() | nil,
          timestamp: String.t() | nil,
          kind: String.t() | nil,
          anchor: String.t() | nil | nil,
          delta: Xberg.RevisionDelta.t()
        }

  defstruct revision_id: nil,
            author: nil,
            timestamp: nil,
            kind: :insertion,
            anchor: nil,
            delta: nil
end
