# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentSummary do
  @moduledoc "Summary of an extracted document."

  @typedoc "Summary of an extracted document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          strategy: String.t() | nil,
          token_count: non_neg_integer() | nil
        }

  defstruct text: nil,
            strategy: :extractive,
            token_count: nil
end
