# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
          start_page: non_neg_integer(),
          end_page: non_neg_integer(),
          confidence: float(),
          reason: String.t() | nil
        }

  defstruct start_page: 0,
            end_page: 0,
            confidence: 0.0,
            reason: :start
end
