# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DocumentMetadata do
  @moduledoc "Metadata about a document for analysis."

  @typedoc "Metadata about a document for analysis."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          size_bytes: non_neg_integer(),
          page_count: non_neg_integer() | nil,
          force_ocr: boolean(),
          user_chunk_config: Xberg.UserChunkConfig.t() | nil,
          chunking_enabled: boolean()
        }

  defstruct mime_type: nil,
            size_bytes: 0,
            page_count: nil,
            force_ocr: false,
            user_chunk_config: nil,
            chunking_enabled: false
end
