# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractedDocument` values."

  @typedoc "The complete diff between two `ExtractedDocument` values."
  @type t :: %__MODULE__{
          content_diff: [Xberg.DiffHunk.t()],
          tables_added: [Xberg.Table.t()],
          tables_removed: [Xberg.Table.t()],
          tables_changed: [Xberg.TableDiff.t()],
          metadata_changed: String.t() | nil,
          embedded_changes: Xberg.EmbeddedChanges.t()
        }

  defstruct content_diff: [],
            tables_added: [],
            tables_removed: [],
            tables_changed: [],
            metadata_changed: nil,
            embedded_changes: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
