# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
