# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractedUri do
  @moduledoc """
  A URI extracted from a document.

  Represents any link, reference, or resource pointer found during extraction.
  The `kind` field classifies the URI semantically, while `label` carries
  optional human-readable display text.
  """

  @typedoc "A URI extracted from a document."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          label: String.t() | nil,
          page: non_neg_integer() | nil,
          kind: String.t() | nil
        }

  defstruct url: nil,
            label: nil,
            page: nil,
            kind: :hyperlink
end
