# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FootnoteDefinition do
  @moduledoc """
  A footnote definition from markdown text.

  Represents `[^label]: content` declarations (including multi-line continuations).
  """

  @typedoc "A footnote definition from markdown text."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: String.t() | nil,
          offset: non_neg_integer()
        }

  defstruct label: nil,
            content: nil,
            offset: 0
end
