# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ImageMetadata do
  @moduledoc """
  Image metadata extracted from image files.

  Includes dimensions, format, and EXIF data.
  """

  @typedoc "Image metadata extracted from image files."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif: %{}

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
