# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: String.t() | nil,
          confidence: float(),
          bbox: Xberg.BBox.t()
        }

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
