# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
