# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  @typedoc "Combined paths to all models needed for OCR (backward compatibility)."
  @type t :: %__MODULE__{
          det_model: String.t() | nil,
          cls_model: String.t() | nil,
          rec_model: String.t() | nil,
          dict_file: String.t() | nil
        }

  defstruct det_model: nil,
            cls_model: nil,
            rec_model: nil,
            dict_file: nil
end
