# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
          page_count: non_neg_integer(),
          pages: [Xberg.PageSignals.t()]
        }

  defstruct page_count: 0,
            pages: []
end
