# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrElementLevel do
  @moduledoc """
  Hierarchical level of an OCR element.

  Maps to Tesseract's page segmentation hierarchy and provides
  equivalent semantics for PaddleOCR.
  """

  @typedoc "Hierarchical level of an OCR element."
  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @doc "Individual word"
  @spec word() :: t()
  def word, do: @word
  @doc "Line of text (default for PaddleOCR)"
  @spec line() :: t()
  def line, do: @line
  @doc "Paragraph or text block"
  @spec block() :: t()
  def block, do: @block
  @doc "Page-level element"
  @spec page() :: t()
  def page, do: @page
end
