# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTable do
  @moduledoc """
  Table detected via OCR.

  Represents a table structure recognized during OCR processing.
  """

  @typedoc "Table detected via OCR."
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: Xberg.OcrTableBoundingBox.t() | nil
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0,
            bounding_box: nil
end
