# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
          left: non_neg_integer(),
          top: non_neg_integer(),
          right: non_neg_integer(),
          bottom: non_neg_integer()
        }

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
