# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageImage do
  @moduledoc "A rendered page ready for inline-base64 transport to the vision model."

  @typedoc "A rendered page ready for inline-base64 transport to the vision model."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          png_bytes: binary()
        }

  defstruct page_number: 0,
            png_bytes: <<>>
end
