# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageBoundary do
  @moduledoc """
  Byte offset boundary for a page.

  Tracks where a specific page's content starts and ends in the main content string,
  enabling mapping from byte positions to page numbers. Offsets are guaranteed to be
  at valid UTF-8 character boundaries when using standard String methods (push_str, push, etc.).
  """

  @typedoc "Byte offset boundary for a page."
  @type t :: %__MODULE__{
          byte_start: non_neg_integer(),
          byte_end: non_neg_integer(),
          page_number: non_neg_integer()
        }

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
