# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
          total_count: non_neg_integer(),
          unit_type: String.t() | nil,
          boundaries: [Xberg.PageBoundary.t()] | nil,
          pages: [Xberg.PageInfo.t()] | nil
        }

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
