# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageSignals do
  @moduledoc "Per-page signals extracted from PDF content."

  @typedoc "Per-page signals extracted from PDF content."
  @type t :: %__MODULE__{
          page_number: non_neg_integer(),
          text_excerpt: String.t() | nil,
          starts_with_letterhead_like: boolean(),
          has_page_number_one_marker: boolean(),
          has_signature_block: boolean(),
          layout_text_density: float()
        }

  defstruct page_number: 0,
            text_excerpt: nil,
            starts_with_letterhead_like: false,
            has_page_number_one_marker: false,
            has_signature_block: false,
            layout_text_density: 0.0
end
