# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageHierarchy do
  @moduledoc """
  Page hierarchy structure containing heading levels and block information.

  Used when PDF text hierarchy extraction is enabled. Contains hierarchical
  blocks with heading levels (H1-H6) for semantic document structure.
  """

  @typedoc "Page hierarchy structure containing heading levels and block information."
  @type t :: %__MODULE__{
          block_count: non_neg_integer(),
          blocks: [Xberg.HierarchicalBlock.t()]
        }

  defstruct block_count: 0,
            blocks: []
end
