# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
          prompt_template: String.t() | nil,
          labels: [String.t()],
          multi_label: boolean(),
          llm: Xberg.LlmConfig.t()
        }

  defstruct prompt_template: nil,
            labels: [],
            multi_label: false,
            llm: nil
end
