# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PresetSample do
  @moduledoc "Pointer to a sample input + its reference output bundled with the preset."

  @typedoc "Pointer to a sample input + its reference output bundled with the preset."
  @type t :: %__MODULE__{
          input_path: String.t() | nil,
          output_path: String.t() | nil
        }

  defstruct input_path: nil,
            output_path: nil
end
