# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
          payload: String.t() | nil,
          confidence: float() | nil,
          bbox: Xberg.QrBoundingBox.t() | nil
        }

  defstruct payload: nil,
            confidence: nil,
            bbox: nil
end
