# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RedactionFinding do
  @moduledoc "One redaction event: which span was rewritten, why, and with what."

  @typedoc "One redaction event: which span was rewritten, why, and with what."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: String.t() | nil,
          strategy: String.t() | nil,
          replacement_token: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            strategy: :mask,
            replacement_token: nil
end
