# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ResolvedPreset do
  @moduledoc """
  A preset merged with caller-supplied overrides (custom schema, prompt suffix,
  context map). Output is what the pipeline orchestrator consumes.
  """

  @typedoc "A preset merged with caller-supplied overrides (custom schema, prompt suffix, context map). Output is what the pipeline orchestrator consumes."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          version: String.t() | nil,
          fingerprint: String.t() | nil,
          schema_name: String.t() | nil,
          schema: String.t() | nil,
          system_prompt: String.t() | nil,
          merge_mode: String.t() | nil,
          preferred_call_mode: String.t() | nil,
          emit_citations: boolean()
        }

  defstruct id: nil,
            version: nil,
            fingerprint: nil,
            schema_name: nil,
            schema: nil,
            system_prompt: nil,
            merge_mode: :object_merge,
            preferred_call_mode: :text_only,
            emit_citations: false
end
