# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SchemaCompliance do
  @moduledoc """
  Schema-validation outcome surfaced as one of three buckets.

  Fold into the combined confidence score without leaking internal validation
  error types.
  """

  @typedoc "Schema-validation outcome surfaced as one of three buckets."
  @type t :: :all_valid | :partial_valid | :all_invalid

  @all_valid :all_valid
  @partial_valid :partial_valid
  @all_invalid :all_invalid

  @doc "Every batch validated against the schema."
  @spec all_valid() :: t()
  def all_valid, do: @all_valid
  @doc "At least one batch validated; at least one did not."
  @spec partial_valid() :: t()
  def partial_valid, do: @partial_valid
  @doc "No batch validated."
  @spec all_invalid() :: t()
  def all_invalid, do: @all_invalid
end
