# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SummarizationConfig do
  @moduledoc "Configuration for the summarisation post-processor."

  @typedoc "Configuration for the summarisation post-processor."
  @type t :: %__MODULE__{
          strategy: String.t() | nil,
          max_tokens: non_neg_integer() | nil,
          llm: Xberg.LlmConfig.t() | nil
        }

  defstruct strategy: :extractive,
            max_tokens: nil,
            llm: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
