# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SummaryStrategy do
  @moduledoc "Summarisation strategy."

  @typedoc "Summarisation strategy."
  @type t :: :extractive | :abstractive

  @extractive :extractive
  @abstractive :abstractive

  @doc "Pure-Rust extractive summary (TextRank over the chunk graph). Deterministic, fast, no external service required."
  @spec extractive() :: t()
  def extractive, do: @extractive
  @doc "Abstractive summary produced by liter-llm. Requires `liter-llm` feature and a configured `LlmConfig`. Token usage is captured in [`ExtractedDocument::llm_usage`](super::extraction::ExtractedDocument::llm_usage)."
  @spec abstractive() :: t()
  def abstractive, do: @abstractive
end
