# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TextDirection do
  @moduledoc "Text direction enumeration for HTML documents."

  @typedoc "Text direction enumeration for HTML documents."
  @type t :: :ltr | :rtl | :auto

  @left_to_right :ltr
  @right_to_left :rtl
  @auto :auto

  @doc "Left-to-right text direction"
  @spec left_to_right() :: t()
  def left_to_right, do: @left_to_right
  @doc "Right-to-left text direction"
  @spec right_to_left() :: t()
  def right_to_left, do: @right_to_left
  @doc "Automatic text direction detection"
  @spec auto() :: t()
  def auto, do: @auto
end
