<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: embedding_backend_management. */
final class EmbeddingBackendManagementTest extends TestCase
{

    /** Clear all embedding backends and verify list is empty */
    public function test_embedding_backends_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearEmbeddingBackends();


    }


    /** List all registered embedding backends */
    public function test_embedding_backends_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listEmbeddingBackends();


    }

}
