<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{

    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearPostProcessors();


    }


    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listPostProcessors();


    }

}
