<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: post_processor_management. */
final class PostProcessorManagementTest extends TestCase
{

    /** Clear all post-processors and verify list is empty */
    public function test_post_processors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearPostProcessors();


    }


    /** List all registered post-processors */
    public function test_post_processors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listPostProcessors();


    }

}
