<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: rerank_async_pending. */
final class RerankAsyncPendingTest extends TestCase
{

    /** rerank_async: plugin model with no backend registered returns an error */
    public function test_async_rerank(): void
    {
        $this->expectException(\Exception::class);        $config = \Kreuzberg\RerankerConfig::from_json(json_encode(["model" => ["name" => "async_rerank", "type" => "plugin"]]));
        Kreuzberg::rerankAsync("neural networks", ["Neural networks are a class of machine learning models inspired by biological brains.", "The Eiffel Tower is located in Paris.", "Convolutional neural networks excel at image recognition tasks."], $config);
    }

}
