<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: reranker_backend_management. */
final class RerankerBackendManagementTest extends TestCase
{

    /** Clear all reranker backends and verify list is empty */
    public function test_clear_reranker_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::clearRerankerBackends();


    }


    /** List all registered reranker backends */
    public function test_list_reranker_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::listRerankerBackends();


    }

}
