<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: summarization. */
final class SummarizationTest extends TestCase
{

    /** TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required. */
    public function test_summarization_extractive_smoke(): void
    {
        $config = \Kreuzberg\ExtractionConfig::from_json(json_encode(["summarization" => ["maxTokens" => 80, "strategy" => "extractive"]]));
        $result = Kreuzberg::extractFileSync("text/book_war_and_peace_1p.txt", null, $config);

            $this->assertEquals("text/plain", trim($result->mimeType));
        // skipped: field 'summary.text' not available on result type        // skipped: field 'summary.strategy' not available on result type

    }

}
