// Generated by alef. Do not edit by hand.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg

/**
 * Email attachment representation.
 *
 * Contains metadata and optionally the content of an email attachment.
 */
data class EmailAttachment(
    /** Attachment name (from Content-Disposition header) */
    val name: String? = null,
    /** Filename of the attachment */
    val filename: String? = null,
    /** MIME type of the attachment */
    val mimeType: String? = null,
    /** Size in bytes */
    val size: Long? = null,
    /** Whether this attachment is an image */
    val isImage: Boolean,
    /**
     * Attachment data (if extracted).
     * Uses `bytes.Bytes` for cheap cloning of large buffers.
     */
    val data: ByteArray? = null,
)
