// Generated by alef. Do not edit by hand.
// alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

import java.nio.file.Path
/** Combined paths to all models needed for OCR (backward compatibility). */
data class ModelPaths(
    /** Path to the detection model directory. */
    val detModel: java.nio.file.Path,
    /** Path to the classification model directory. */
    val clsModel: java.nio.file.Path,
    /** Path to the recognition model directory. */
    val recModel: java.nio.file.Path,
    /** Path to the character dictionary file. */
    val dictFile: java.nio.file.Path,
)
