// Generated by alef. Do not edit by hand.
// alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1

package dev.kreuzberg

object RendererBridge {
    private val registered = mutableMapOf<String, IRenderer>()

    fun register(impl: IRenderer): Unit {
        val name = impl.name()
        registered[name] = impl
        KreuzbergBridge.nativeRegisterRenderer(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        KreuzbergBridge.nativeUnregisterRenderer(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        KreuzbergBridge.nativeClearRenderers()
    }

    fun getAll(): Map<String, IRenderer> = registered.toMap()
}
