// Generated by alef. Do not edit by hand.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148

package dev.kreuzberg

object RerankerBackendBridge {
    private val registered = mutableMapOf<String, IRerankerBackend>()

    fun register(impl: IRerankerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        KreuzbergBridge.nativeRegisterRerankerBackend(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        KreuzbergBridge.nativeUnregisterRerankerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        KreuzbergBridge.nativeClearRerankerBackends()
    }

    fun getAll(): Map<String, IRerankerBackend> = registered.toMap()
}
