// Generated by alef. Do not edit by hand.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.kreuzberg

/** Per-category running counter for `RedactionStrategy.TokenReplace`. */
class TokenCounter internal constructor(internal val handle: Long) : AutoCloseable {
    override fun close() { KreuzbergBridge.nativeFreeTokenCounter(handle) }
}
