// Generated by alef. Do not edit by hand.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg

/**
 * Application properties from docProps/app.xml for XLSX
 *
 * Contains Excel-specific document metadata.
 */
data class XlsxAppProperties(
    /** Application name (e.g., "Microsoft Excel") */
    val application: String? = null,
    /** Application version */
    val appVersion: String? = null,
    /** Document security level */
    val docSecurity: Int? = null,
    /** Scale crop flag */
    val scaleCrop: Boolean? = null,
    /** Links up to date flag */
    val linksUpToDate: Boolean? = null,
    /** Shared document flag */
    val sharedDoc: Boolean? = null,
    /** Hyperlinks changed flag */
    val hyperlinksChanged: Boolean? = null,
    /** Company name */
    val company: String? = null,
    /** Worksheet names */
    val worksheetNames: List<String> = emptyList(),
)
