// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        let result = try Kreuzberg.clearOcrBackends()
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

    func testOcrBackendsUnregister() throws {
        // Unregister nonexistent OCR backend gracefully
        let result = try Kreuzberg.unregisterOcrBackend(name: "nonexistent-backend-xyz")
    }

}
