// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9b5427d2c3040a597006a411669c129c21a8f76c79a2ec871137029de6301188
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try Kreuzberg.getExtensionsForMime(mimeType: "application/pdf")
    }

}
