// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
