// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException
{
    public DeserializeException(string message) : base(message) { }

    public DeserializeException(string message, Exception innerException) : base(message, innerException) { }
}
