// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException
{
    public DeserializeException(string message) : base(message) { }

    public DeserializeException(string message, Exception innerException) : base(message, innerException) { }
}
