// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Type of list detection.
/// </summary>
[JsonConverter(typeof(ListTypeJsonConverter))]
public enum ListType
{
    /// <summary>
    /// Bullet points (-, *, •, etc.)
    /// </summary>
    [JsonPropertyName("Bullet")]
    Bullet,
    /// <summary>
    /// Numbered lists (1., 2., etc.)
    /// </summary>
    [JsonPropertyName("Numbered")]
    Numbered,
    /// <summary>
    /// Lettered lists (a., b., A., B., etc.)
    /// </summary>
    [JsonPropertyName("Lettered")]
    Lettered,
    /// <summary>
    /// Indented items
    /// </summary>
    [JsonPropertyName("Indented")]
    Indented,
}


/// <summary>
/// Custom JSON converter for <see cref="ListType"/> that respects explicit variant names.
/// </summary>
internal sealed class ListTypeJsonConverter : JsonConverter<ListType>
{
    public override ListType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        var value = reader.GetString();
        return value switch
        {
            "Bullet" => ListType.Bullet,
            "Numbered" => ListType.Numbered,
            "Lettered" => ListType.Lettered,
            "Indented" => ListType.Indented,
            _ => throw new JsonException($"Unknown ListType value: {value}")
        };
    }

    public override void Write(Utf8JsonWriter writer, ListType value, JsonSerializerOptions options)
    {
        var str = value switch
        {
            ListType.Bullet => "Bullet",
            ListType.Numbered => "Numbered",
            ListType.Lettered => "Lettered",
            ListType.Indented => "Indented",
            _ => throw new JsonException($"Unknown ListType value: {value}")
        };
        writer.WriteStringValue(str);
    }
}
