// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
