// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException
{
    public PdfAnalysisErrorException(string message) : base(message) { }

    public PdfAnalysisErrorException(string message, Exception innerException) : base(message, innerException) { }
}
