// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException
{
    public SchemaNotObjectException(string message) : base(message) { }

    public SchemaNotObjectException(string message, Exception innerException) : base(message, innerException) { }
}
