// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
