// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The document's MIME type is not supported by any registered extractor.
/// </summary>
public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
