// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9f1aa8902588c29cba58e2c9ded7d1ab9df683c9d98d68122641f69f9ad3ae48
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { createRequire } from "module";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

// Patch CommonJS `require('env')` and `require('wasi_snapshot_preview1')` to
// return shim objects. wasm-pack `--target nodejs` emits bare `require()`
// calls for these from getrandom/wasi transitives, but they are not real
// Node modules — the WASM module imports them by name and the host is
// expected to satisfy them. Patch Module._load BEFORE the wasm bundle is
// imported by any test file.
// Note: setupFiles run per-test-worker; vitest imports the test files
// AFTER setupFiles complete, so this hook installs in time.
{
  const _require = createRequire(import.meta.url);
  const Module = _require("module");
  // env.system / env.mkstemp come from C-runtime calls embedded in some
  // WASM-compiled deps (e.g. tesseract-wasm). Tests that don't exercise
  // those paths only need the imports to be callable for module instantiation.
  const env = {
    system: (_cmd: number) => -1,
    mkstemp: (_template: number) => -1,
  };
  // WASI shims. Critical: clock_time_get and random_get must produce realistic
  // values — returning 0 for all clock calls causes WASM-side timing loops to
  // spin forever (e.g. getrandom's spin-until-elapsed retry), and zero-filled
  // random buffers can cause init loops in deps expecting non-zero entropy.
  const _wasiMemoryView = (): DataView | null => {
    // Imports are wired before the WASM is instantiated; the bundle stashes
    // its instance on a runtime-known global once available. We try to grab
    // it lazily so writes to wasm memory go to the right place.
    const g = globalThis as unknown as { __kreuzberg_wasm_memory__?: WebAssembly.Memory };
    return g.__kreuzberg_wasm_memory__ ? new DataView(g.__kreuzberg_wasm_memory__.buffer) : null;
  };
  const _cryptoFill = (buf: Uint8Array) => {
    const c = globalThis.crypto;
    if (c && typeof c.getRandomValues === "function") c.getRandomValues(buf);
    else for (let i = 0; i < buf.length; i++) buf[i] = Math.floor(Math.random() * 256);
  };
  const wasi_snapshot_preview1 = {
    proc_exit: () => {},
    environ_get: () => 0,
    environ_sizes_get: (countOut: number, _sizeOut: number) => {
      const v = _wasiMemoryView();
      if (v) v.setUint32(countOut, 0, true);
      return 0;
    },
    fd_write: () => 0,
    fd_read: () => 0,
    fd_seek: () => 0,
    fd_close: () => 0,
    fd_prestat_get: () => 8, // EBADF — no preopens.
    fd_prestat_dir_name: () => 0,
    fd_fdstat_get: () => 0,
    fd_fdstat_set_flags: () => 0,
    path_open: () => 44, // ENOENT.
    path_create_directory: () => 0,
    path_remove_directory: () => 0,
    path_unlink_file: () => 0,
    path_filestat_get: () => 44, // ENOENT.
    path_rename: () => 0,
    clock_time_get: (_clockId: number, _precision: bigint, timeOut: number) => {
      const ns = BigInt(Date.now()) * 1_000_000n + (BigInt(performance.now() | 0) % 1_000_000n);
      const v = _wasiMemoryView();
      if (v) v.setBigUint64(timeOut, ns, true);
      return 0;
    },
    clock_res_get: (_clockId: number, resOut: number) => {
      const v = _wasiMemoryView();
      if (v) v.setBigUint64(resOut, 1_000n, true);
      return 0;
    },
    random_get: (bufPtr: number, bufLen: number) => {
      const g = globalThis as unknown as { __kreuzberg_wasm_memory__?: WebAssembly.Memory };
      if (!g.__kreuzberg_wasm_memory__) return 0;
      _cryptoFill(new Uint8Array(g.__kreuzberg_wasm_memory__.buffer, bufPtr, bufLen));
      return 0;
    },
    args_get: () => 0,
    args_sizes_get: (countOut: number, _sizeOut: number) => {
      const v = _wasiMemoryView();
      if (v) v.setUint32(countOut, 0, true);
      return 0;
    },
    poll_oneoff: () => 0,
    sched_yield: () => 0,
  };
  const _origResolve = Module._resolveFilename;
  Module._resolveFilename = function (request: string, parent: unknown, ...rest: unknown[]) {
    if (request === "env" || request === "wasi_snapshot_preview1") return request;
    return _origResolve.call(this, request, parent, ...rest);
  };
  const _origLoad = Module._load;
  Module._load = function (request: string, parent: unknown, ...rest: unknown[]) {
    if (request === "env") return env;
    if (request === "wasi_snapshot_preview1") return wasi_snapshot_preview1;
    return _origLoad.call(this, request, parent, ...rest);
  };
}

// Change to the configured test-documents directory so that fixture file paths like
// "pdf/fake_memo.pdf" resolve correctly when vitest runs from e2e/wasm/.
// setup.ts lives in e2e/wasm/; the fixtures dir lives at the repository root,
// two directories up: e2e/wasm/ -> e2e/ -> repo root.
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const testDocumentsDir = join(__dirname, "..", "..", "test_documents");
process.chdir(testDocumentsDir);
