// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 30000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		setupFiles: ["./setup.ts"],
	},
});
