/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RerankerBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  rerank?(query: string, documents: string): string;
}

export class RerankerBackendAdapter {
  constructor(private bridge: RerankerBackendBridge) {}

  async rerank(query: string, documents: string): Promise<string> {
    try {
      const result = await this.bridge.rerank(query, documents);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
