/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface ValidatorBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  validate?(result: string, config: string): string;
  shouldValidate(result: string, config: string): string;
  priority(): string;
}

export class ValidatorAdapter {
  constructor(private bridge: ValidatorBridge) {}

  async validate(result: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.validate(result, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async shouldValidate(result: string, config: string): Promise<string> {
    try {
      const result = await this.bridge.shouldValidate(result, config);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async priority(): Promise<string> {
    try {
      const result = await this.bridge.priority();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
