# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management

test_that("embedding_backends_clear: Clear all embedding backends and verify list is empty", {
  invisible(clear_embedding_backends())
  expect_true(TRUE)
})

test_that("embedding_backends_list: List all registered embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})
