// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : XbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
