// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
