// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Image decoding or PNG re-encoding failed.
/// </summary>
public class ImageException : RasterizeErrorException
{
    public ImageException(string message) : base(message) { }

    public ImageException(string message, Exception innerException) : base(message, innerException) { }
}
