// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : XbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
