// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
