// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// JSON or MessagePack serialization/deserialization failed.
/// </summary>
public class SerializationException : XbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
