// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Invalid configuration or input parameters were supplied.
/// </summary>
public class ValidationException : XbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
