// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
#nullable enable

using System;

namespace Xberg;

public class XbergException : Exception
{
    public int Code { get; }

    public XbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public XbergException(string message) : base(message)
    {
        Code = 0;
    }

    public XbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
