<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Xberg;

/**
 * Token → original PII text.
 */
final class RehydrationMap
{
}
