<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
