<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
