# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzberg
  ## The version string for this package.
  VERSION = "5.0.0.pre.rc.6"
end
