// DO NOT EDIT - auto-generated by alef
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
package dev.kreuzberg;

/**
 * The extraction was cancelled via a `CancellationToken`.
 */
public class CancelledException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new CancelledException with the given message. */
  public CancelledException(final String message) {
    super(message);
  }

  /** Creates a new CancelledException with the given message and cause. */
  public CancelledException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
