// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

/**
 * Classification enrichment knob: how to label the document.
 */
public record ClassificationEnrichmentConfig(PageClassificationConfig config) {
}
