// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Diff for a single embedded archive entry that appears in both results.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EmbeddedDiff.Builder.class)
@SuppressWarnings("PMD")
public record EmbeddedDiff(
    @JsonProperty("path") String path,
    @JsonProperty("diff") ExtractionDiff diff
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String path = "";
private ExtractionDiff diff = null;

        /** Sets the path field. */
        @JsonProperty("path")
        public Builder withPath(final String value) {
            this.path = value;
            return this;
        }

        /** Sets the diff field. */
        @JsonProperty("diff")
        public Builder withDiff(final ExtractionDiff value) {
            this.diff = value;
            return this;
        }

        /** Builds the EmbeddedDiff instance. */
        public EmbeddedDiff build() {
            return new EmbeddedDiff(
                path,
                diff
            );
        }
    }
    // CPD-ON
}
