// DO NOT EDIT - auto-generated by alef
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
package dev.kreuzberg;

/**
 * The preset's declared `id` does not match its file-system location.
 */
public class IdMismatchException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IdMismatchException with the given message. */
  public IdMismatchException(final String message) {
    super(message);
  }

  /** Creates a new IdMismatchException with the given message and cause. */
  public IdMismatchException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
