// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Image extraction configuration.
 */
@SuppressWarnings({"PMD.ShortVariable", "PMD.LongVariable"})
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageExtractionConfig.Builder.class)
public record ImageExtractionConfig(
    @Nullable @JsonProperty("extract_images") Boolean extractImages,
    @Nullable @JsonProperty("target_dpi") Integer targetDpi,
    @Nullable @JsonProperty("max_image_dimension") Integer maxImageDimension,
    @Nullable @JsonProperty("inject_placeholders") Boolean injectPlaceholders,
    @Nullable @JsonProperty("auto_adjust_dpi") Boolean autoAdjustDpi,
    @Nullable @JsonProperty("min_dpi") Integer minDpi,
    @Nullable @JsonProperty("max_dpi") Integer maxDpi,
    @Nullable @JsonProperty("max_images_per_page") Integer maxImagesPerPage,
    @Nullable @JsonProperty("classify") Boolean classify,
    @Nullable @JsonProperty("include_page_rasters") Boolean includePageRasters,
    @Nullable @JsonProperty("run_ocr_on_images") Boolean runOcrOnImages,
    @Nullable @JsonProperty("ocr_text_only") Boolean ocrTextOnly,
    @Nullable @JsonProperty("append_ocr_text") Boolean appendOcrText,
    @Nullable @JsonProperty("output_format") ImageOutputFormat outputFormat,
    @Nullable @JsonProperty("svg") SvgOptions svg
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }
    public ImageExtractionConfig{
        if (targetDpi == null) { targetDpi = 300; }
        if (maxImageDimension == null) { maxImageDimension = 4096; }
        if (minDpi == null) { minDpi = 72; }
        if (maxDpi == null) { maxDpi = 600; }
    }

    // CPD-OFF
    /** Jackson builder for ImageExtractionConfig deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        /** extractImages. */
        @JsonProperty("extract_images")
        private final Boolean extractImages;
        /** targetDpi. */
        @JsonProperty("target_dpi")
        private final Integer targetDpi;
        /** maxImageDimension. */
        @JsonProperty("max_image_dimension")
        private final Integer maxImageDimension;
        /** injectPlaceholders. */
        @JsonProperty("inject_placeholders")
        private final Boolean injectPlaceholders;
        /** autoAdjustDpi. */
        @JsonProperty("auto_adjust_dpi")
        private final Boolean autoAdjustDpi;
        /** minDpi. */
        @JsonProperty("min_dpi")
        private final Integer minDpi;
        /** maxDpi. */
        @JsonProperty("max_dpi")
        private final Integer maxDpi;
        /** maxImagesPerPage. */
        @JsonProperty("max_images_per_page")
        private final Integer maxImagesPerPage;
        /** classify. */
        private final Boolean classify;
        /** includePageRasters. */
        @JsonProperty("include_page_rasters")
        private final Boolean includePageRasters;
        /** runOcrOnImages. */
        @JsonProperty("run_ocr_on_images")
        private final Boolean runOcrOnImages;
        /** ocrTextOnly. */
        @JsonProperty("ocr_text_only")
        private final Boolean ocrTextOnly;
        /** appendOcrText. */
        @JsonProperty("append_ocr_text")
        private final Boolean appendOcrText;
        /** outputFormat. */
        @JsonProperty("output_format")
        @Nullable         private final ImageOutputFormat outputFormat = new ImageOutputFormat.Native();
        /** svg. */
        @Nullable         private final SvgOptions svg;

        /** Sets the extractImages field. */
        @JsonProperty("extract_images")
        public Builder withExtractImages(final @Nullable Boolean value) {
            this.extractImages = value;
            return this;
        }

        /** Sets the targetDpi field. */
        @JsonProperty("target_dpi")
        public Builder withTargetDpi(final @Nullable Integer value) {
            this.targetDpi = value;
            return this;
        }

        /** Sets the maxImageDimension field. */
        @JsonProperty("max_image_dimension")
        public Builder withMaxImageDimension(final @Nullable Integer value) {
            this.maxImageDimension = value;
            return this;
        }

        /** Sets the injectPlaceholders field. */
        @JsonProperty("inject_placeholders")
        public Builder withInjectPlaceholders(final @Nullable Boolean value) {
            this.injectPlaceholders = value;
            return this;
        }

        /** Sets the autoAdjustDpi field. */
        @JsonProperty("auto_adjust_dpi")
        public Builder withAutoAdjustDpi(final @Nullable Boolean value) {
            this.autoAdjustDpi = value;
            return this;
        }

        /** Sets the minDpi field. */
        @JsonProperty("min_dpi")
        public Builder withMinDpi(final @Nullable Integer value) {
            this.minDpi = value;
            return this;
        }

        /** Sets the maxDpi field. */
        @JsonProperty("max_dpi")
        public Builder withMaxDpi(final @Nullable Integer value) {
            this.maxDpi = value;
            return this;
        }

        /** Sets the maxImagesPerPage field. */
        @JsonProperty("max_images_per_page")
        public Builder withMaxImagesPerPage(final @Nullable Integer value) {
            this.maxImagesPerPage = value;
            return this;
        }

        /** Sets the classify field. */
        @JsonProperty("classify")
        public Builder withClassify(final @Nullable Boolean value) {
            this.classify = value;
            return this;
        }

        /** Sets the includePageRasters field. */
        @JsonProperty("include_page_rasters")
        public Builder withIncludePageRasters(final @Nullable Boolean value) {
            this.includePageRasters = value;
            return this;
        }

        /** Sets the runOcrOnImages field. */
        @JsonProperty("run_ocr_on_images")
        public Builder withRunOcrOnImages(final @Nullable Boolean value) {
            this.runOcrOnImages = value;
            return this;
        }

        /** Sets the ocrTextOnly field. */
        @JsonProperty("ocr_text_only")
        public Builder withOcrTextOnly(final @Nullable Boolean value) {
            this.ocrTextOnly = value;
            return this;
        }

        /** Sets the appendOcrText field. */
        @JsonProperty("append_ocr_text")
        public Builder withAppendOcrText(final @Nullable Boolean value) {
            this.appendOcrText = value;
            return this;
        }

        /** Sets the outputFormat field. */
        @JsonProperty("output_format")
        public Builder withOutputFormat(final @Nullable ImageOutputFormat value) {
            this.outputFormat = value;
            return this;
        }

        /** Sets the svg field. */
        @JsonProperty("svg")
        public Builder withSvg(final @Nullable SvgOptions value) {
            this.svg = value;
            return this;
        }

        /** Constructs a ImageExtractionConfig instance from the builder's current state. */
        public ImageExtractionConfig build() {
            return new ImageExtractionConfig(
                extractImages,
                targetDpi,
                maxImageDimension,
                injectPlaceholders,
                autoAdjustDpi,
                minDpi,
                maxDpi,
                maxImagesPerPage,
                classify,
                includePageRasters,
                runOcrOnImages,
                ocrTextOnly,
                appendOcrText,
                outputFormat,
                svg
            );
        }
    }
    // CPD-ON
    /**
     * Factory method for defaultInstance.
     */
    public static ImageExtractionConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
