// DO NOT EDIT - auto-generated by alef
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
package dev.kreuzberg;

/**
 * A file system or I/O operation failed. These errors always bubble up unchanged.
 */
public class IoException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoException with the given message. */
  public IoException(final String message) {
    super(message);
  }

  /** Creates a new IoException with the given message and cause. */
  public IoException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
