// DO NOT EDIT - auto-generated by alef
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
package dev.kreuzberg;

/**
 * An internal `Mutex` or `RwLock` was found in a poisoned state.
 */
public class LockPoisonedException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new LockPoisonedException with the given message. */
  public LockPoisonedException(final String message) {
    super(message);
  }

  /** Creates a new LockPoisonedException with the given message and cause. */
  public LockPoisonedException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
