// DO NOT EDIT - auto-generated by alef
// alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
