// DO NOT EDIT - auto-generated by alef
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
package dev.kreuzberg;

/**
 * An OCR engine returned an error or produced unusable output.
 */
public class OcrException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new OcrException with the given message. */
  public OcrException(final String message) {
    super(message);
  }

  /** Creates a new OcrException with the given message and cause. */
  public OcrException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
