// DO NOT EDIT - auto-generated by alef
// alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
package dev.kreuzberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
