// DO NOT EDIT - auto-generated by alef
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
package dev.kreuzberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParsingException with the given message. */
  public ParsingException(final String message) {
    super(message);
  }

  /** Creates a new ParsingException with the given message and cause. */
  public ParsingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
