// DO NOT EDIT - auto-generated by alef
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
package dev.kreuzberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) {
    super(message);
  }

  /** Creates a new PdfAnalysisErrorException with the given message and cause. */
  public PdfAnalysisErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
