// This file is auto-generated by alef — DO NOT EDIT.
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Application properties from docProps/app.xml for PPTX
 *
 * Contains PowerPoint-specific document metadata.
 */
@SuppressWarnings({"PMD.LongVariable"})
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PptxAppProperties.Builder.class)
public record PptxAppProperties(
    @Nullable @JsonProperty("application") String application,
    @Nullable @JsonProperty("app_version") String appVersion,
    @Nullable @JsonProperty("total_time") Integer totalTime,
    @Nullable @JsonProperty("company") String company,
    @Nullable @JsonProperty("doc_security") Integer docSecurity,
    @Nullable @JsonProperty("scale_crop") Boolean scaleCrop,
    @Nullable @JsonProperty("links_up_to_date") Boolean linksUpToDate,
    @Nullable @JsonProperty("shared_doc") Boolean sharedDoc,
    @Nullable @JsonProperty("hyperlinks_changed") Boolean hyperlinksChanged,
    @Nullable @JsonProperty("slides") Integer slides,
    @Nullable @JsonProperty("notes") Integer notes,
    @Nullable @JsonProperty("hidden_slides") Integer hiddenSlides,
    @Nullable @JsonProperty("multimedia_clips") Integer multimediaClips,
    @Nullable @JsonProperty("presentation_format") String presentationFormat,
    @JsonProperty("slide_titles") List<String> slideTitles
) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for PptxAppProperties deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        /** application. */
        private final String application;
        /** appVersion. */
        @JsonProperty("app_version")
        private final String appVersion;
        /** totalTime. */
        @JsonProperty("total_time")
        private final Integer totalTime;
        /** company. */
        private final String company;
        /** docSecurity. */
        @JsonProperty("doc_security")
        private final Integer docSecurity;
        /** scaleCrop. */
        @JsonProperty("scale_crop")
        private final Boolean scaleCrop;
        /** linksUpToDate. */
        @JsonProperty("links_up_to_date")
        private final Boolean linksUpToDate;
        /** sharedDoc. */
        @JsonProperty("shared_doc")
        private final Boolean sharedDoc;
        /** hyperlinksChanged. */
        @JsonProperty("hyperlinks_changed")
        private final Boolean hyperlinksChanged;
        /** slides. */
        private final Integer slides;
        /** notes. */
        private final Integer notes;
        /** hiddenSlides. */
        @JsonProperty("hidden_slides")
        private final Integer hiddenSlides;
        /** multimediaClips. */
        @JsonProperty("multimedia_clips")
        private final Integer multimediaClips;
        /** presentationFormat. */
        @JsonProperty("presentation_format")
        private final String presentationFormat;
        /** slideTitles. */
        @JsonProperty("slide_titles")
        private final List<String> slideTitles = List.of();

        /** Sets the application field. */
        @JsonProperty("application")
        public Builder withApplication(final @Nullable String value) {
            this.application = value;
            return this;
        }

        /** Sets the appVersion field. */
        @JsonProperty("app_version")
        public Builder withAppVersion(final @Nullable String value) {
            this.appVersion = value;
            return this;
        }

        /** Sets the totalTime field. */
        @JsonProperty("total_time")
        public Builder withTotalTime(final @Nullable int value) {
            this.totalTime = value;
            return this;
        }

        /** Sets the company field. */
        @JsonProperty("company")
        public Builder withCompany(final @Nullable String value) {
            this.company = value;
            return this;
        }

        /** Sets the docSecurity field. */
        @JsonProperty("doc_security")
        public Builder withDocSecurity(final @Nullable int value) {
            this.docSecurity = value;
            return this;
        }

        /** Sets the scaleCrop field. */
        @JsonProperty("scale_crop")
        public Builder withScaleCrop(final @Nullable boolean value) {
            this.scaleCrop = value;
            return this;
        }

        /** Sets the linksUpToDate field. */
        @JsonProperty("links_up_to_date")
        public Builder withLinksUpToDate(final @Nullable boolean value) {
            this.linksUpToDate = value;
            return this;
        }

        /** Sets the sharedDoc field. */
        @JsonProperty("shared_doc")
        public Builder withSharedDoc(final @Nullable boolean value) {
            this.sharedDoc = value;
            return this;
        }

        /** Sets the hyperlinksChanged field. */
        @JsonProperty("hyperlinks_changed")
        public Builder withHyperlinksChanged(final @Nullable boolean value) {
            this.hyperlinksChanged = value;
            return this;
        }

        /** Sets the slides field. */
        @JsonProperty("slides")
        public Builder withSlides(final @Nullable int value) {
            this.slides = value;
            return this;
        }

        /** Sets the notes field. */
        @JsonProperty("notes")
        public Builder withNotes(final @Nullable int value) {
            this.notes = value;
            return this;
        }

        /** Sets the hiddenSlides field. */
        @JsonProperty("hidden_slides")
        public Builder withHiddenSlides(final @Nullable int value) {
            this.hiddenSlides = value;
            return this;
        }

        /** Sets the multimediaClips field. */
        @JsonProperty("multimedia_clips")
        public Builder withMultimediaClips(final @Nullable int value) {
            this.multimediaClips = value;
            return this;
        }

        /** Sets the presentationFormat field. */
        @JsonProperty("presentation_format")
        public Builder withPresentationFormat(final @Nullable String value) {
            this.presentationFormat = value;
            return this;
        }

        /** Sets the slideTitles field. */
        @JsonProperty("slide_titles")
        public Builder withSlideTitles(final List<String> value) {
            this.slideTitles = value;
            return this;
        }

        /** Constructs a PptxAppProperties instance from the builder's current state. */
        public PptxAppProperties build() {
            return new PptxAppProperties(
                application,
                appVersion,
                totalTime,
                company,
                docSecurity,
                scaleCrop,
                linksUpToDate,
                sharedDoc,
                hyperlinksChanged,
                slides,
                notes,
                hiddenSlides,
                multimediaClips,
                presentationFormat,
                slideTitles
            );
        }
    }
    // CPD-ON
}
