// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * High-level category used to group presets in the registry UI.
 */
@SuppressWarnings("PMD")
public enum PresetCategory {
    /**
     * Invoices, receipts, statements, purchase orders, W-9.
     */
    Finance("finance"),
    /**
     * Passports, drivers licenses, insurance cards.
     */
    Identity("identity"),
    /**
     * Contracts, NDAs, agreements.
     */
    Legal("legal"),
    /**
     * Bills of lading, customs declarations, packing lists.
     */
    Logistics("logistics"),
    /**
     * Clinical records, lab reports.
     */
    Medical("medical"),
    /**
     * Pay stubs, resumes, employment offers.
     */
    Hr("hr"),
    /**
     * Catch-all for documents that don't fit the other categories.
     */
    Other("other");


    /** The string value. */
    private final String value;

    PresetCategory(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PresetCategory fromValue(final String value) {
        for (PresetCategory e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown PresetCategory value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
