// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Outlook PST archive metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PstMetadata.Builder.class)
@SuppressWarnings("PMD")
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("message_count")
private long messageCount = 0;

        /** Sets the messageCount field. */
        @JsonProperty("message_count")
        public Builder withMessageCount(final long value) {
            this.messageCount = value;
            return this;
        }

        /** Builds the PstMetadata instance. */
        public PstMetadata build() {
            return new PstMetadata(
                messageCount
            );
        }
    }
    // CPD-ON
}
