// DO NOT EDIT - auto-generated by alef
// alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
package dev.kreuzberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) {
    super(message);
  }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
