// DO NOT EDIT - auto-generated by alef
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
package dev.kreuzberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RerankingException with the given message. */
  public RerankingException(final String message) {
    super(message);
  }

  /** Creates a new RerankingException with the given message and cause. */
  public RerankingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
