// DO NOT EDIT - auto-generated by alef
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
package dev.kreuzberg;

/**
 * A security policy was violated (e.g. zip bomb, oversized archive).
 */
public class SecurityException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SecurityException with the given message. */
  public SecurityException(final String message) {
    super(message);
  }

  /** Creates a new SecurityException with the given message and cause. */
  public SecurityException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
