// DO NOT EDIT - auto-generated by alef
// alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
package dev.kreuzberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends KreuzbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new TranscriptionException with the given message. */
  public TranscriptionException(final String message) {
    super(message);
  }

  /** Creates a new TranscriptionException with the given message and cause. */
  public TranscriptionException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
