// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Supported Whisper model sizes.
 *
 * These map to published ONNX exports on Hugging Face (onnx-community or
 * similar orgs). The actual filenames and repos are resolved inside the
 * transcription engine.
 */
@SuppressWarnings("PMD")
public enum WhisperModel {
    /**
     * Smallest, fastest, lowest quality. Good default for development and CI.
     */
    Tiny("tiny"),
    /**
     * Reasonable quality/speed tradeoff.
     */
    Base("base"),
    /**
     * Better accuracy with higher memory and cache use.
     */
    Small("small"),
    /**
     * High quality; slower and more memory-intensive.
     */
    Medium("medium"),
    /**
     * Best quality (large-v3). Use only when latency and memory use are acceptable.
     */
    LargeV3("large_v3");


    /** The string value. */
    private final String value;

    WhisperModel(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static WhisperModel fromValue(final String value) {
        for (WhisperModel e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown WhisperModel value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
