# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "kreuzberg/version"
require_relative "kreuzberg/native"

# Top-level namespace for the Kreuzberg Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "kreuzberg/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Kreuzberg
  # Re-export all types and functions from native extension
end
