// Generated by alef. Do not edit by hand.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1

package io.xberg

/// Bridge adapter for IEmbeddingBackend implementations.
///
/// Wraps a user-supplied IEmbeddingBackend instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class EmbeddingBackendAdapter(private val impl: IEmbeddingBackend) : IEmbeddingBackend {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()

    override fun dimensions(): Long {
        return impl.dimensions()
    }

    override suspend fun embed(texts: List<String>): List<List<Float>> {
        return impl.embed(texts)
    }
}
