// Generated by alef. Do not edit by hand.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Unified extraction result envelope. */
data class ExtractionResult(
    /** Extracted documents in discovery order. */
    val results: List<ExtractedDocument> = emptyList(),
    /** Non-fatal per-input errors. */
    val errors: List<ExtractionErrorItem> = emptyList(),
    /** Aggregate counts for the operation. */
    val summary: ExtractionSummary = ExtractionSummary(),
    /** Final URLs reached after redirects during URL ingestion. */
    val crawlFinalUrls: List<String> = emptyList(),
    /** Total redirects followed while fetching or crawling URLs. */
    val crawlRedirectCount: Long = 0L,
    /** Unique normalized URLs discovered by crawls. */
    val crawlUniqueNormalizedUrls: List<String> = emptyList(),
)
