// Generated by alef. Do not edit by hand.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** One redaction event: which span was rewritten, why, and with what. */
data class RedactionFinding(
    /** Byte-offset start in the original (pre-redaction) `ExtractedDocument.content`. */
    val start: Int,
    /** Byte-offset end (exclusive) in the original `ExtractedDocument.content`. */
    val end: Int,
    /** PII category that fired this redaction. */
    val category: PiiCategory,
    /** Strategy applied to this finding (mask, hash, token-replace, drop). */
    val strategy: RedactionStrategy,
    /**
     * String that replaced the original mention. Always present; for `Drop` the replacement is the
     * empty string.
     */
    val replacementToken: String,
)
