// Generated by alef. Do not edit by hand.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * One user-supplied literal term to redact.
 *
 * Matched as a regex-escaped substring (so callers do not need to escape metacharacters
 * themselves). Case-insensitive by default — set `Self.case_sensitive` to `true` for exact
 * byte-match semantics.
 */
data class RedactionTerm(
    /** Custom category label surfaced in `RedactionFinding.category`. */
    val label: String,
    /** Literal value to match. Regex metacharacters are escaped automatically. */
    val value: String,
    /** When `true`, match the value as-is; otherwise match ASCII-case-insensitively. */
    val caseSensitive: Boolean,
)
