// Generated by alef. Do not edit by hand.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1

package io.xberg

object RendererBridge {
    private val registered = mutableMapOf<String, IRenderer>()

    fun register(impl: IRenderer): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterRenderer(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterRenderer(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearRenderers()
    }

    fun getAll(): Map<String, IRenderer> = registered.toMap()
}
