// Generated by alef. Do not edit by hand.
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** SSRF policy configuration. */
data class SsrfPolicy(
    /** If true, reject URLs that resolve to private/metadata IP ranges. */
    val denyPrivate: Boolean = true,
    /**
     * Allowed hostnames and IP ranges. Empty means deny all unless `deny_private` is false.
     *
     * Phase 1: skipped from language bindings — `HostMatcher`'s untagged-enum FFI form is not yet
     * decided. Expose in a follow-up once the tagged-enum representation is finalized.
     */
    val allowlist: List<String>? = null,
    /** Maximum number of HTTP redirects to follow during validation. */
    val maxRedirects: Byte = 5,
    /**
     * Allowed URI schemes. Default: `["http", "https"]`. Not serialized (set at runtime). Skipped
     * from language bindings — `HashSet<&'static str>` is FFI-hostile.
     */
    val schemeAllowlist: List<String>? = null,
)
