// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d4a1450d60183634e7feb9398cabddef7d385577b3fbec889b4f5cd20945e583
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Image extraction configuration.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImageExtractionConfig.Builder.class)
public record ImageExtractionConfig(
    /**
     * Extract images from documents
     */
    @Nullable @JsonProperty("extract_images") Boolean extractImages,
    /**
     * Target DPI for image normalization
     */
    @Nullable @JsonProperty("target_dpi") Integer targetDpi,
    /**
     * Maximum dimension for images (width or height)
     */
    @Nullable @JsonProperty("max_image_dimension") Integer maxImageDimension,
    /**
     * Whether to inject image reference placeholders into markdown output.
     * When {@code true} (default), image references like {@code ![Image 1](embedded:p1_i0)}
     * are appended to the markdown. Set to {@code false} to extract images as data
     * without polluting the markdown output.
     */
    @Nullable @JsonProperty("inject_placeholders") Boolean injectPlaceholders,
    /**
     * Automatically adjust DPI based on image content
     */
    @Nullable @JsonProperty("auto_adjust_dpi") Boolean autoAdjustDpi,
    /**
     * Minimum DPI threshold
     */
    @Nullable @JsonProperty("min_dpi") Integer minDpi,
    /**
     * Maximum DPI threshold
     */
    @Nullable @JsonProperty("max_dpi") Integer maxDpi,
    /**
     * Maximum number of image objects to extract per PDF page.
     *
     * Some PDFs (e.g. technical diagrams stored as thousands of raster fragments)
     * can trigger extremely long or indefinite extraction times when every image
     * object on a dense page is decoded individually via the PDF extractor. Setting this
     * limit causes kreuzberg to stop collecting individual images once the count
     * per page reaches the cap and emit a warning instead.
     *
     * {@code None} (default) means no limit — all images are extracted.
     */
    @Nullable @JsonProperty("max_images_per_page") Integer maxImagesPerPage,
    /**
     * When {@code true} (default), extracted images are classified by kind and grouped
     * into clusters where they appear to belong to one figure.
     */
    @Nullable Boolean classify
) {
    public static Builder builder() {
        return new Builder();
    }
    public ImageExtractionConfig{
        if (targetDpi == null) targetDpi = 300;
        if (maxImageDimension == null) maxImageDimension = 4096;
        if (minDpi == null) minDpi = 72;
        if (maxDpi == null) maxDpi = 600;
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

        @JsonProperty("extract_images")
private Boolean extractImages = null;
        @JsonProperty("target_dpi")
private Integer targetDpi = null;
        @JsonProperty("max_image_dimension")
private Integer maxImageDimension = null;
        @JsonProperty("inject_placeholders")
private Boolean injectPlaceholders = null;
        @JsonProperty("auto_adjust_dpi")
private Boolean autoAdjustDpi = null;
        @JsonProperty("min_dpi")
private Integer minDpi = null;
        @JsonProperty("max_dpi")
private Integer maxDpi = null;
        @JsonProperty("max_images_per_page")
private Optional<Integer> maxImagesPerPage = Optional.empty();
private Boolean classify = null;

        /** Sets the extractImages field. */
        @JsonProperty("extract_images")
        public Builder withExtractImages(final boolean value) {
            this.extractImages = value;
            return this;
        }

        /** Sets the targetDpi field. */
        @JsonProperty("target_dpi")
        public Builder withTargetDpi(final int value) {
            this.targetDpi = value;
            return this;
        }

        /** Sets the maxImageDimension field. */
        @JsonProperty("max_image_dimension")
        public Builder withMaxImageDimension(final int value) {
            this.maxImageDimension = value;
            return this;
        }

        /** Sets the injectPlaceholders field. */
        @JsonProperty("inject_placeholders")
        public Builder withInjectPlaceholders(final boolean value) {
            this.injectPlaceholders = value;
            return this;
        }

        /** Sets the autoAdjustDpi field. */
        @JsonProperty("auto_adjust_dpi")
        public Builder withAutoAdjustDpi(final boolean value) {
            this.autoAdjustDpi = value;
            return this;
        }

        /** Sets the minDpi field. */
        @JsonProperty("min_dpi")
        public Builder withMinDpi(final int value) {
            this.minDpi = value;
            return this;
        }

        /** Sets the maxDpi field. */
        @JsonProperty("max_dpi")
        public Builder withMaxDpi(final int value) {
            this.maxDpi = value;
            return this;
        }

        /** Sets the maxImagesPerPage field. */
        @JsonProperty("max_images_per_page")
        public Builder withMaxImagesPerPage(final @Nullable Integer value) {
            this.maxImagesPerPage = Optional.ofNullable(value);
            return this;
        }

        /** Sets the classify field. */
        public Builder withClassify(final boolean value) {
            this.classify = value;
            return this;
        }

        /** Builds the ImageExtractionConfig instance. */
        public ImageExtractionConfig build() {
            return new ImageExtractionConfig(
                extractImages,
                targetDpi,
                maxImageDimension,
                injectPlaceholders,
                autoAdjustDpi,
                minDpi,
                maxDpi,
                maxImagesPerPage.orElse(null),
                classify
            );
        }
    }
    // CPD-ON
    public static ImageExtractionConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
