// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:902655e7ffaf464112817ae65109efb9a3b60083a50c39c1c5210e44de2898ce
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Processing options for tree-sitter code analysis.
 *
 * Controls which analysis features are enabled when extracting code files.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TreeSitterProcessConfig.Builder.class)
public record TreeSitterProcessConfig(
    /**
     * Extract structural items (functions, classes, structs, etc.). Default: true.
     */
    @Nullable Boolean structure,
    /**
     * Extract import statements. Default: true.
     */
    @Nullable Boolean imports,
    /**
     * Extract export statements. Default: true.
     */
    @Nullable Boolean exports,
    /**
     * Extract comments. Default: false.
     */
    @Nullable Boolean comments,
    /**
     * Extract docstrings. Default: false.
     */
    @Nullable Boolean docstrings,
    /**
     * Extract symbol definitions. Default: false.
     */
    @Nullable Boolean symbols,
    /**
     * Include parse diagnostics. Default: false.
     */
    @Nullable Boolean diagnostics,
    /**
     * Maximum chunk size in bytes. {@code None} disables chunking.
     */
    @Nullable @JsonProperty("chunk_max_size") Long chunkMaxSize,
    /**
     * Content rendering mode for code extraction.
     */
    @Nullable @JsonProperty("content_mode") CodeContentMode contentMode
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with")
    public static final class Builder {

private Boolean structure = null;
private Boolean imports = null;
private Boolean exports = null;
private Boolean comments = null;
private Boolean docstrings = null;
private Boolean symbols = null;
private Boolean diagnostics = null;
        @JsonProperty("chunk_max_size")
private Optional<Long> chunkMaxSize = Optional.empty();
        @JsonProperty("content_mode")
        @Nullable private CodeContentMode contentMode = CodeContentMode.Chunks;

        /** Sets the structure field. */
        public Builder withStructure(final boolean value) {
            this.structure = value;
            return this;
        }

        /** Sets the imports field. */
        public Builder withImports(final boolean value) {
            this.imports = value;
            return this;
        }

        /** Sets the exports field. */
        public Builder withExports(final boolean value) {
            this.exports = value;
            return this;
        }

        /** Sets the comments field. */
        public Builder withComments(final boolean value) {
            this.comments = value;
            return this;
        }

        /** Sets the docstrings field. */
        public Builder withDocstrings(final boolean value) {
            this.docstrings = value;
            return this;
        }

        /** Sets the symbols field. */
        public Builder withSymbols(final boolean value) {
            this.symbols = value;
            return this;
        }

        /** Sets the diagnostics field. */
        public Builder withDiagnostics(final boolean value) {
            this.diagnostics = value;
            return this;
        }

        /** Sets the chunkMaxSize field. */
        @JsonProperty("chunk_max_size")
        public Builder withChunkMaxSize(final @Nullable Long value) {
            this.chunkMaxSize = Optional.ofNullable(value);
            return this;
        }

        /** Sets the contentMode field. */
        @JsonProperty("content_mode")
        public Builder withContentMode(final CodeContentMode value) {
            this.contentMode = value;
            return this;
        }

        /** Builds the TreeSitterProcessConfig instance. */
        public TreeSitterProcessConfig build() {
            return new TreeSitterProcessConfig(
                structure,
                imports,
                exports,
                comments,
                docstrings,
                symbols,
                diagnostics,
                chunkMaxSize.orElse(null),
                contentMode
            );
        }
    }
    // CPD-ON
    public static TreeSitterProcessConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
