# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc """
  Batch item for byte array extraction.

  Used with `batch_extract_bytes` and `batch_extract_bytes_sync`
  to represent a single item in a batch extraction job.
  """

  @typedoc "Batch item for byte array extraction."
  @type t :: %__MODULE__{
          content: binary(),
          mime_type: String.t() | nil,
          config: map() | nil
        }

  defstruct content: <<>>,
            mime_type: nil,
            config: nil
end
