# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
