# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          confidence: float() | nil
        }

  defstruct label: nil,
            confidence: nil
end
