# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.CodeContentMode do
  @moduledoc """
  Content rendering mode for code extraction.

  Controls how extracted code content is represented in the `content` field
  of `ExtractionResult`.
  """

  @typedoc "Content rendering mode for code extraction."
  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @doc "Use TSLP semantic chunks as content (default)."
  @spec chunks() :: t()
  def chunks, do: @chunks
  @doc "Use raw source code as content."
  @spec raw() :: t()
  def raw, do: @raw
  @doc "Emit function/class headings + docstrings (no code bodies)."
  @spec structure() :: t()
  def structure, do: @structure
end
