# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ConfidenceSignals do
  @moduledoc """
  Input signals for confidence scoring.

  Caller fills these from the extraction result and the LLM response.
  """

  @typedoc "Input signals for confidence scoring."
  @type t :: %__MODULE__{
          text_coverage: float(),
          ocr_aggregate: float() | nil,
          schema_compliance: String.t() | nil
        }

  defstruct text_coverage: 0.0,
            ocr_aggregate: nil,
            schema_compliance: :all_valid
end
