# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bcc59fa925874b81a1c614eaeee7629aef443086c456032bc36ffd51d4322aa1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
