# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  @typedoc "MIME type detection response."
  @type t :: %__MODULE__{
          mime_type: String.t() | nil,
          filename: String.t() | nil
        }

  defstruct mime_type: nil,
            filename: nil
end
