# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil
end
