# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  @typedoc "Image element in Djot."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil
end
