# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  @typedoc "Link element in Djot."
  @type t :: %__MODULE__{
          url: String.t() | nil,
          text: String.t() | nil,
          title: String.t() | nil
        }

  defstruct url: nil,
            text: nil,
            title: nil
end
