# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentBoundary do
  @moduledoc "Detected document boundary within a PDF."

  @typedoc "Detected document boundary within a PDF."
  @type t :: %__MODULE__{
          start_page: non_neg_integer(),
          end_page: non_neg_integer(),
          confidence: float(),
          reason: String.t() | nil
        }

  defstruct start_page: 0,
            end_page: 0,
            confidence: 0.0,
            reason: :start
end
