# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  @typedoc "A resolved relationship between two nodes in the document tree."
  @type t :: %__MODULE__{
          source: non_neg_integer(),
          target: non_neg_integer(),
          kind: String.t() | nil
        }

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
