# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Element do
  @moduledoc """
  Semantic element extracted from document.

  Represents a logical unit of content with semantic classification,
  unique identifier, and metadata for tracking origin and position.
  """

  @typedoc "Semantic element extracted from document."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          text: String.t() | nil,
          metadata: map()
        }

  defstruct element_type: :title,
            text: nil,
            metadata: nil
end
