# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: map() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
