# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Entity do
  @moduledoc "A single named entity detected in the extracted text."

  @typedoc "A single named entity detected in the extracted text."
  @type t :: %__MODULE__{
          category: String.t() | nil,
          text: String.t() | nil,
          start: non_neg_integer(),
          end: non_neg_integer(),
          confidence: float() | nil
        }

  defstruct category: :person,
            text: nil,
            start: 0,
            end: 0,
            confidence: nil
end
