# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExcelSheet do
  @moduledoc """
  Single Excel worksheet.

  Represents one sheet from an Excel workbook with its content
  converted to Markdown format and dimensional statistics.
  """

  @typedoc "Single Excel worksheet."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          markdown: String.t() | nil,
          row_count: non_neg_integer(),
          col_count: non_neg_integer(),
          cell_count: non_neg_integer(),
          table_cells: [[String.t()]] | nil
        }

  defstruct name: nil,
            markdown: nil,
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
