# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [map()]
        }

  defstruct label: nil,
            content: []
end
