# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [map()]
        }

  defstruct headings: []
end
