# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9384adf82dc01493f6dd9b50d65dd3f82d57dbe50f58f939f9ba57665c316916
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil
end
