# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc """
  Image preprocessing configuration for OCR.

  These settings control how images are preprocessed before OCR to improve
  text recognition quality. Different preprocessing strategies work better
  for different document types.
  """

  @typedoc "Image preprocessing configuration for OCR."
  @type t :: %__MODULE__{
          target_dpi: integer(),
          auto_rotate: boolean(),
          deskew: boolean(),
          denoise: boolean(),
          contrast_enhance: boolean(),
          binarization_method: String.t() | nil,
          invert_colors: boolean()
        }

  defstruct target_dpi: 300,
            auto_rotate: false,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
