# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            metadata: nil
end
