# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            metadata: nil
end
