# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ListType do
  @moduledoc "Type of list detection."

  @typedoc "Type of list detection."
  @type t :: :bullet | :numbered | :lettered | :indented

  @bullet :bullet
  @numbered :numbered
  @lettered :lettered
  @indented :indented

  @doc "Bullet points (-, *, •, etc.)"
  @spec bullet() :: t()
  def bullet, do: @bullet
  @doc "Numbered lists (1., 2., etc.)"
  @spec numbered() :: t()
  def numbered, do: @numbered
  @doc "Lettered lists (a., b., A., B., etc.)"
  @spec lettered() :: t()
  def lettered, do: @lettered
  @doc "Indented items"
  @spec indented() :: t()
  def indented, do: @indented
end
