# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.MetaSchema do
  @moduledoc "Compiled meta-schema validator over `preset.schema.json`."

  alias Kreuzberg.Native
  defstruct [:ref]

  @typedoc "Compiled meta-schema validator over `preset.schema.json`."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Compile the given JSON text as a Draft 2020-12 meta-schema."
  def compile(meta_schema_json) do
    ref = Native.metaschema_compile(meta_schema_json)
    %__MODULE__{ref: ref}
  end

  @doc "Validate `raw` against the meta-schema and deserialize into a [`Preset`],"
  def parse_preset(obj, path, raw) do
    Native.metaschema_parse_preset(obj.ref, path, raw)
  end
end
