# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
          page_count: non_neg_integer(),
          pages: [map()]
        }

  defstruct page_count: 0,
            pages: []
end
