# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried.
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
          stages: [map()],
          quality_thresholds: map()
        }

  defstruct stages: [],
            quality_thresholds: nil
end
