# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
          left: non_neg_integer(),
          top: non_neg_integer(),
          right: non_neg_integer(),
          bottom: non_neg_integer()
        }

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
