# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried.
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
          stages: [map()],
          quality_thresholds: map()
        }

  defstruct stages: [],
            quality_thresholds: nil
end
