# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  @typedoc "Bounding box for an OCR-detected table in pixel coordinates."
  @type t :: %__MODULE__{
          left: non_neg_integer(),
          top: non_neg_integer(),
          right: non_neg_integer(),
          bottom: non_neg_integer()
        }

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
