# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageBoundary do
  @moduledoc """
  Byte offset boundary for a page.

  Tracks where a specific page's content starts and ends in the main content string,
  enabling mapping from byte positions to page numbers. Offsets are guaranteed to be
  at valid UTF-8 character boundaries when using standard String methods (push_str, push, etc.).
  """

  @typedoc "Byte offset boundary for a page."
  @type t :: %__MODULE__{
          byte_start: non_neg_integer(),
          byte_end: non_neg_integer(),
          page_number: non_neg_integer()
        }

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
