# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageUnitType do
  @moduledoc """
  Type of paginated unit in a document.

  Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
  """

  @typedoc "Type of paginated unit in a document."
  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @doc "Standard document pages (PDF, DOCX, images)"
  @spec page() :: t()
  def page, do: @page
  @doc "Presentation slides (PPTX, ODP)"
  @spec slide() :: t()
  def slide, do: @slide
  @doc "Spreadsheet sheets (XLSX, ODS)"
  @spec sheet() :: t()
  def sheet, do: @sheet
end
