# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PdfMetadata do
  @moduledoc """
  PDF-specific metadata.

  Contains metadata fields specific to PDF documents that are not in the common
  `Metadata` structure. Common fields like title, authors, keywords, and dates
  are at the `Metadata` level.
  """

  @typedoc "PDF-specific metadata."
  @type t :: %__MODULE__{
          pdf_version: String.t() | nil,
          producer: String.t() | nil,
          is_encrypted: boolean() | nil,
          width: integer() | nil,
          height: integer() | nil,
          page_count: non_neg_integer() | nil
        }

  defstruct pdf_version: nil,
            producer: nil,
            is_encrypted: nil,
            width: nil,
            height: nil,
            page_count: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
