# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
