# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct x: 0,
            y: 0,
            width: 0,
            height: 0
end
