# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionReport do
  @moduledoc """
  Audit report describing what the redaction processor found and how it replaced it.

  The redactor returns this alongside the rewritten content so compliance, replay, and
  audit-log consumers can see exactly what fired. Offsets are relative to the *original*
  pre-redaction `content` and are intended for audit reconstruction only — the original
  bytes are dropped at the end of the pipeline.
  """

  @typedoc "Audit report describing what the redaction processor found and how it replaced it."
  @type t :: %__MODULE__{
          findings: [map()],
          total_redacted: non_neg_integer()
        }

  defstruct findings: [],
            total_redacted: 0
end
