# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionReport do
  @moduledoc """
  Audit report describing what the redaction processor found and how it replaced it.

  The redactor returns this alongside the rewritten content so compliance, replay, and
  audit-log consumers can see exactly what fired. Offsets are relative to the *original*
  pre-redaction `content` and are intended for audit reconstruction only — the original
  bytes are dropped at the end of the pipeline.
  """

  @typedoc "Audit report describing what the redaction processor found and how it replaced it."
  @type t :: %__MODULE__{
          findings: [map()],
          total_redacted: non_neg_integer()
        }

  defstruct findings: [],
            total_redacted: 0
end
