# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RerankedDocument do
  @moduledoc """
  A single document returned by the reranker, with its position in the input and score.

  `index` maps back to the caller's original document list, so metadata arrays
  (e.g. IDs, paths) can be reordered without passing them through the reranker.

  Since v5.0.0.
  """

  @typedoc "A single document returned by the reranker, with its position in the input and score."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          score: float(),
          document: String.t() | nil
        }

  defstruct index: 0,
            score: 0.0,
            document: nil
end
