# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:825fa0762b70ef9d34d143c3149e07237bc91f018af8f9b1525484c5d414a47d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Segment do
  @moduledoc "A text segment with its byte offset in the original document."

  @typedoc "A text segment with its byte offset in the original document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          byte_start: non_neg_integer()
        }

  defstruct text: nil,
            byte_start: 0
end
