# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @typedoc "Structured data type classification."
  @type t :: :"json-ld" | :microdata | :rdfa

  @json_ld :"json-ld"
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD structured data"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "Microdata"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDFa"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
