# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Kreuzberg.Native

  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_default()}
  end

  @doc "Allocate the next token for `category` and `original`. If the original"
  def next_token(obj, category, original) do
    Native.tokencounter_next_token(obj.ref, category, original)
  end

  def default() do
    ref = Native.tokencounter_default()
    %__MODULE__{ref: ref}
  end
end
