# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  @typedoc "YAKE-specific parameters."
  @type t :: %__MODULE__{
          window_size: non_neg_integer()
        }

  defstruct window_size: 2

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
