// DO NOT EDIT - auto-generated by alef
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new BadMetaSchemaException with the given message. */
    public BadMetaSchemaException(final String message) {
        super(message);
    }

    /** Creates a new BadMetaSchemaException with the given message and cause. */
    public BadMetaSchemaException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
