// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * A batch of pages ready for a single vision-LLM call.
 */
public record Batch(
    @JsonInclude(JsonInclude.Include.NON_NULL) List<PageImage> pages,
    @Nullable @JsonProperty("user_text") String userText
) {
}
