// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * A batch of pages ready for a single vision-LLM call.
 */
public record Batch(
    @JsonInclude(JsonInclude.Include.NON_NULL) List<PageImage> pages,
    @Nullable @JsonProperty("user_text") String userText
) {
}
