// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Both views of the fused output: citation-wrapped and flattened.
 */
public record CitationOutput(
    @JsonProperty("structured_output") Object structuredOutput,
    @JsonProperty("structured_output_flat") Object structuredOutputFlat
) {
}
