// DO NOT EDIT - auto-generated by alef
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
package io.xberg;

/**
 * The file validates but cannot be deserialized into [`Preset`].
 */
public class DeserializeException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new DeserializeException with the given message. */
  public DeserializeException(final String message) {
    super(message);
  }

  /** Creates a new DeserializeException with the given message and cause. */
  public DeserializeException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
