// DO NOT EDIT - auto-generated by alef
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
package io.xberg;

/**
 * The embedding model or embedding pipeline returned an error.
 */
public class EmbeddingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new EmbeddingException with the given message. */
  public EmbeddingException(final String message) {
    super(message);
  }

  /** Creates a new EmbeddingException with the given message and cause. */
  public EmbeddingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
