// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Source kind for ExtractInput.
 */
@SuppressWarnings("PMD")
public enum ExtractInputKind {
    /**
     * Raw in-memory bytes.
     */
    Bytes("bytes"),
    /**
     * A filesystem path, {@code file://} URI, or HTTP(S) URL.
     */
    Uri("uri");


    /** The string value. */
    private final String value;

    ExtractInputKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExtractInputKind fromValue(final String value) {
        for (ExtractInputKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ExtractInputKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
