// DO NOT EDIT - auto-generated by alef
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new HeuristicsErrorException with the given message. */
  public HeuristicsErrorException(final String message) {
    super(message);
  }

  /** Creates a new HeuristicsErrorException with the given message and cause. */
  public HeuristicsErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
