// DO NOT EDIT - auto-generated by alef
// alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
package io.xberg;

/**
 * Errors that can occur during heuristics analysis.
 */
public class HeuristicsErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new HeuristicsErrorException with the given message. */
    public HeuristicsErrorException(final String message) {
        super(message);
    }

    /** Creates a new HeuristicsErrorException with the given message and cause. */
    public HeuristicsErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
