// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Image type classification.
 */
@SuppressWarnings("PMD")
public enum ImageType {
    /**
     * Data URI image
     */
    DataUri("data-uri"),
    /**
     * Inline SVG
     */
    InlineSvg("inline-svg"),
    /**
     * External image URL
     */
    External("external"),
    /**
     * Relative path image
     */
    Relative("relative");


    /** The string value. */
    private final String value;

    ImageType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ImageType fromValue(final String value) {
        for (ImageType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ImageType value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
