// DO NOT EDIT - auto-generated by alef
// alef:hash:4742e34a3fe39cffeef22d79924d9ae81187dfe1f56bc4751da860cef7620ea7
package io.xberg;

/**
 * An image manipulation operation (resize, decode, DPI conversion) failed.
 */
public class ImageProcessingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
