// DO NOT EDIT - auto-generated by alef
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
package io.xberg;

/**
 * A file system or I/O operation failed. These errors always bubble up unchanged.
 */
public class IoException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoException with the given message. */
  public IoException(final String message) {
    super(message);
  }

  /** Creates a new IoException with the given message and cause. */
  public IoException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
