// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/**
 * Minimal identifier for a downloadable model.
 *
 * The {@code kind} is the canonical model-type key understood by the underlying
 * model manager (e.g. {@code "rtdetr"}, {@code "tatr"}, {@code "pp_doclayout_v3"},
 * {@code "table_classifier"}, {@code "slanet_wired"}).
 */
public record ModelId(String kind) {
}
