// DO NOT EDIT - auto-generated by alef
// alef:hash:350ae5725f1360a336e35cba3e068d84a71c9fa0d1644e646b1021e0ad1dc3f1
package io.xberg;

/**
 * A catch-all for uncommon errors that do not fit another variant.
 */
public class OtherException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
