// DO NOT EDIT - auto-generated by alef
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
package io.xberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParsingException with the given message. */
  public ParsingException(final String message) {
    super(message);
  }

  /** Creates a new ParsingException with the given message and cause. */
  public ParsingException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
