// DO NOT EDIT - auto-generated by alef
// alef:hash:ba4891420890dfe62dccd502c47241a86b32a9b766e5c105e631be2b79108697
package io.xberg;

/**
 * PDF parsing or page rendering failed.
 */
public class PdfException extends RasterizeErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfException with the given message. */
  public PdfException(final String message) {
    super(message);
  }

  /** Creates a new PdfException with the given message and cause. */
  public PdfException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
