// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Outlook PST archive metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PstMetadata.Builder.class)
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    /** Creates a new Builder for constructing instances of this record. */
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    /** Jackson builder for PstMetadata deserialization. */
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("message_count")
        private long messageCount;

        /** Sets the messageCount field. */
        @JsonProperty("message_count")
        public Builder withMessageCount(final long value) {
            this.messageCount = value;
            return this;
        }

        /** Constructs a PstMetadata instance from the builder's current state. */
        public PstMetadata build() {
            return new PstMetadata(
                messageCount
            );
        }
    }
    // CPD-ON
}
