// DO NOT EDIT - auto-generated by alef
// alef:hash:83ef6721bd185da9c840598c4f06480ad2c2b1a6612099585e1640628c279b5f
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) {
    super(message);
  }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
