# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'document_extractor_management' do
  it 'document_extractors_clear: Clear all document extractors and verify list is empty' do
    Kreuzberg.clear_document_extractors()

  end

  it 'extractors_list: List all registered document extractors' do
    result = Kreuzberg.list_document_extractors()

    expect(result).not_to be_nil
  end
end
