# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'embed_extra' do
  it 'embed_texts_batch: Batch embed texts' do
    result = Kreuzberg.embed_texts_async(['Hello', 'World'], {model: { 'name' => 'balanced', 'type' => 'preset' }})

    expect(result).not_to be_nil
  end
end
