# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'embed_async_pending' do
  it 'embed_texts_async_empty_input: embed_texts_async: empty text list' do
    result = Kreuzberg.embed_texts_async([], {model: { 'name' => 'balanced', 'type' => 'preset' }})
    expect(result.length).to eq(0)

    expect(result).not_to be_nil
  end

  it 'embed_texts_async_happy: embed_texts_async: basic async embedding' do
    result = Kreuzberg.embed_texts_async(['First', 'Second'], {model: { 'name' => 'balanced', 'type' => 'preset' }})
    expect(result.length).to be >= 2

    expect(result).not_to be_nil
  end

  it 'embed_texts_async_preset_switch: embed_texts_async: preset override' do
    result = Kreuzberg.embed_texts_async(['Text'], {model: { 'name' => 'balanced', 'type' => 'preset' }})

    expect(result).not_to be_nil
  end
end
