# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c615c2117a65d484cacb297cfa5555d7e2a5066e8a3cec9e6525dca008f91148
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'embed_extra' do
  it 'embed_texts_batch: Batch embed texts' do
    result = Kreuzberg.embed_texts_async(['Hello', 'World'], {model: { 'name' => 'balanced', 'type' => 'preset' }})

    expect(result).not_to be_nil
  end
end
