# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'ocr_backend_management' do
  it 'ocr_backends_clear: Clear all OCR backends and verify list is empty' do
    Kreuzberg.clear_ocr_backends()

  end

  it 'ocr_backends_list: List all registered OCR backends' do
    result = Kreuzberg.list_ocr_backends()

    expect(result).not_to be_nil
  end

  it 'ocr_backends_unregister: Unregister nonexistent OCR backend gracefully' do
    Kreuzberg.unregister_ocr_backend('nonexistent-backend-xyz')

  end
end
