# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:41108829b76e0c81d2550b3d782dbcfe333433c1ef760105074ca1ae3861c822
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'pdf' do
  it 'render_pdf_page_first: render_pdf_page_to_png: first page' do
    pdf_bytes = File.read("pdf/fake_memo.pdf").bytes
    result = Kreuzberg.render_pdf_page_to_png(pdf_bytes, 0)
    expect(result.length).to be >= 100

  end

  it 'render_pdf_page_out_of_range: render_pdf_page_to_png: page out of range' do
    expect {
      pdf_bytes = File.read("pdf/fake_memo.pdf").bytes
      Kreuzberg.render_pdf_page_to_png(pdf_bytes, 999)
    }.to raise_error(RuntimeError)
  end
end
