# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9b5427d2c3040a597006a411669c129c21a8f76c79a2ec871137029de6301188
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'pdf' do
  it 'render_pdf_page_first: render_pdf_page_to_png: first page' do
    pdf_bytes = File.read("pdf/fake_memo.pdf").bytes
    result = Kreuzberg.render_pdf_page_to_png(pdf_bytes, 0)
    expect(result.length).to be >= 100

  end

  it 'render_pdf_page_out_of_range: render_pdf_page_to_png: page out of range' do
    expect {
      pdf_bytes = File.read("pdf/fake_memo.pdf").bytes
      Kreuzberg.render_pdf_page_to_png(pdf_bytes, 999)
    }.to raise_error(RuntimeError)
  end
end
