// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbeddingBackendsClear(t *testing.T) {
	// Clear all embedding backends and verify list is empty
	_ = kreuzberg.ClearEmbeddingBackends()
}

func Test_EmbeddingBackendsList(t *testing.T) {
	// List all registered embedding backends
	_, err := kreuzberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
