// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1865aced39145e92bc65e9f4ca999b62f1f2b003e5fe0ed4bd2b1050a8f64a0f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbeddingBackendsClear(t *testing.T) {
	// Clear all embedding backends and verify list is empty
	_ = kreuzberg.ClearEmbeddingBackends()
}

func Test_EmbeddingBackendsList(t *testing.T) {
	// List all registered embedding backends
	_, err := kreuzberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
