// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e352a3241ad9a4dbb9d8de3d7e9d4a38d07adf42de9f3eaa6df3f657057a8da
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	_ = xberg.ClearRenderers()
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := xberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
