// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a54f64851961a3fb236133a70906c9b22add934583f1997edc3fadb1fb89ff4d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg
import dev.kreuzberg.RerankerBackendBridge

/** E2e tests for category: reranker_backend_management. */
class RerankerBackendManagementTest {

    companion object {
        init {
            try {
                System.loadLibrary("kreuzberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load kreuzberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testClearRerankerBackends() = runBlocking {
        // Clear all reranker backends and verify list is empty
        val result = RerankerBackendBridge.clearAll()
    }

    @Test
    fun testListRerankerBackends() = runBlocking {
        // List all registered reranker backends
        val result = Kreuzberg.listRerankerBackends()
    }

}
