// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ec589c98257f946746f32f356af0bf116faae656ea7ac64554724cb202b68ff1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import dev.kreuzberg.Kreuzberg

/** E2e tests for category: validator_management. */
class ValidatorManagementTest {
    @Test
    fun testValidatorsClear() = runBlocking {
        // Clear all validators and verify list is empty
        val result = ValidatorBridge.clearAll()
    }

    @Test
    fun testValidatorsList() = runBlocking {
        // List all registered validators
        val result = Kreuzberg.listValidators()
    }

}
